<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use TCG\Voyager\Models\DataRow;


class CustomDataRowsTableSeeder extends Seeder
{
    public function run()
    {
        $dataRows = [
            array(
                "id" => 77,
                "data_type_id" =>7,
                "field" => "id",
                "type" => "number",
                "display_name" => "Id",
                "required" => 1,
                "browse" => 0,
                "read" => 0,
                "edit" => 0,
                "add" => 0,
                "delete" => 0,
                "details" => "{}",
                "order" => 1,
            ),
            array(
                "id" => 75,
                "data_type_id" => 7,
                "field" => "name",
                "type" => "text",
                "display_name" => "Name",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 2,
            ),
            array(
                "id" => 76,
                "data_type_id" => 7,
                "field" => "surname",
                "type" => "text",
                "display_name" => "Surname",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 3,
            ),
            array(
                "id" => 77,
                "data_type_id" => 7,
                "field" => "email",
                "type" => "text",
                "display_name" => "Email",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 7,
            ),
            array(
                "id" => 78,
                "data_type_id" => 7,
                "field" => "password",
                "type" => "text",
                "display_name" => "Password",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 5,
            ),
            array(
                "id" => 79,
                "data_type_id" => 7,
                "field" => "adress",
                "type" => "text",
                "display_name" => "Adress",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 6,
            ),
            array(
                "id" => 80,
                "data_type_id" => 7,
                "field" => "phone",
                "type" => "number",
                "display_name" => "Phone",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 7,
            ),
            array(
                "id" => 81,
                "data_type_id" => 7,
                "field" => "image",
                "type" => "text",
                "display_name" => "Image",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 8,
            ),
            array(
                "id" => 82,
                "data_type_id" => 7,
                "field" => "status",
                "type" => "checkbox",
                "display_name" => "Status",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 9,
            ),
            array(
                "id" => 83,
                "data_type_id" => 7,
                "field" => "created_at",
                "type" => "timestamp",
                "display_name" => "Created At",
                "required" => 0,
                "browse" => 0,
                "read" => 0,
                "edit" => 0,
                "add" => 0,
                "delete" => 0,
                "details" => "{}",
                "order" => 10,
            ),
            array(
                "id" => 87,
                "data_type_id" => 7,
                "field" => "updated_at",
                "type" => "timestamp",
                "display_name" => "Updated At",
                "required" => 0,
                "browse" => 0,
                "read" => 0,
                "edit" => 0,
                "add" => 0,
                "delete" => 0,
                "details" => "{}",
                "order" => 11,
            ),
            array(
                "id" => 85,
                "data_type_id" => 6,
                "field" => "id",
                "type" => "number",
                "display_name" => "Id",
                "required" => 1,
                "browse" => 0,
                "read" => 0,
                "edit" => 0,
                "add" => 0,
                "delete" => 0,
                "details" => "{}",
                "order" => 1,
            ),
            array(
                "id" => 86,
                "data_type_id" => 6,
                "field" => "trainer_id",
                "type" => "number",
                "display_name" => "Trainer",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 2,
            ),
            array(
                "id" => 87,
                "data_type_id" => 6,
                "field" => "title",
                "type" => "text",
                "display_name" => "Title",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 3,
            ),
            array(
                "id" => 88,
                "data_type_id" => 6,
                "field" => "description",
                "type" => "text",
                "display_name" => "Description",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 5,
            ),
            array(
                "id" => 89,
                "data_type_id" => 6,
                "field" => "price",
                "type" => "number",
                "display_name" => "Price",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 6,
            ),
            array(
                "id" => 90,
                "data_type_id" => 6,
                "field" => "image",
                "type" => "image",
                "display_name" => "Image",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 7,
            ),
            array(
                "id" => 91,
                "data_type_id" => 6,
                "field" => "rating",
                "type" => "number",
                "display_name" => "Rating",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 8,
            ),
            array(
                "id" => 92,
                "data_type_id" => 6,
                "field" => "length",
                "type" => "number",
                "display_name" => "Length",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 9,
            ),
            array(
                "id" => 93,
                "data_type_id" => 6,
                "field" => "duraction",
                "type" => "text",
                "display_name" => "Duraction",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 10,
            ),
            array(
                "id" => 97,
                "data_type_id" => 6,
                "field" => "diffucity",
                "type" => "text",
                "display_name" => "Diffucity",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 11,
            ),
            array(
                "id" => 95,
                "data_type_id" => 6,
                "field" => "body_foucs",
                "type" => "text",
                "display_name" => "Body Foucs",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 12,
            ),
            array(
                "id" => 96,
                "data_type_id" => 6,
                "field" => "trainer_type",
                "type" => "text",
                "display_name" => "Trainer Type",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 13,
            ),
            array(
                "id" => 97,
                "data_type_id" => 6,
                "field" => "created_at",
                "type" => "timestamp",
                "display_name" => "Created At",
                "required" => 0,
                "browse" => 1,
                "read" => 0,
                "edit" => 0,
                "add" => 0,
                "delete" => 0,
                "details" => "{}",
                "order" => 7,
            ),
            array(
                "id" => 98,
                "data_type_id" => 6,
                "field" => "updated_at",
                "type" => "timestamp",
                "display_name" => "Updated At",
                "required" => 0,
                "browse" => 0,
                "read" => 0,
                "edit" => 0,
                "add" => 0,
                "delete" => 0,
                "details" => "{}",
                "order" => 6,
            ),
            array(
                "id" => 120,
                "data_type_id" => 6,
                "field" => "paket_belongsto_trainer_relationship",
                "type" => "relationship",
                "display_name" => "Trainers",
                "required" => 0,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
//                "details" => "{\"model\":\"App\\\\Models\\\\Trainer\",\"table\":\"trainers\",\"type\":\"belongsTo\",\"column\":\"trainer_id\",\"key\":\"id\",\"label\":\"name\",\"pivot_table\":\"categories\",\"pivot\":\"0\",\"taggable\":\"0\"}",
                'details'      => [
                    'model'       => 'App\\Models\\Trainer',
                    'table'       => 'trainers',
                    'type'        => 'belongsTo',
                    'column'      => 'trainer_id',
                    'key'         => 'id',
                    'label'       => 'name',
                    'pivot_table' => 'categories',
                    'pivot'       => '0 ',
                    'taggable'    => '0',
                ],

                "order" => 7,
            ),
            array(
                "id" => 99,
                "data_type_id" => 5,
                "field" => "id",
                "type" => "number",
                "display_name" => "Id",
                "required" => 1,
                "browse" => 0,
                "read" => 0,
                "edit" => 0,
                "add" => 0,
                "delete" => 0,
                "details" => "{}",
                "order" => 1,
            ),
            array(
                "id" => 100,
                "data_type_id" => 5,
                "field" => "title",
                "type" => "text",
                "display_name" => "Title",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 2,
            ),
            array(
                "id" => 101,
                "data_type_id" => 5,
                "field" => "content",
                "type" => "text",
                "display_name" => "Content",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 3,
            ),
            array(
                "id" => 102,
                "data_type_id" => 5,
                "field" => "image",
                "type" => "image",
                "display_name" => "Image",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 7,
            ),
            array(
                "id" => 103,
                "data_type_id" => 5,
                "field" => "status",
                "type" => "checkbox",
                "display_name" => "Status",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 5,
            ),
            array(
                "id" => 107,
                "data_type_id" => 5,
                "field" => "created_at",
                "type" => "timestamp",
                "display_name" => "Created At",
                "required" => 0,
                "browse" => 1,
                "read" => 0,
                "edit" => 0,
                "add" => 0,
                "delete" => 0,
                "details" => "{}",
                "order" => 6,
            ),
            array(
                "id" => 105,
                "data_type_id" => 5,
                "field" => "updated_at",
                "type" => "timestamp",
                "display_name" => "Updated At",
                "required" => 0,
                "browse" => 0,
                "read" => 0,
                "edit" => 0,
                "add" => 0,
                "delete" => 0,
                "details" => "{}",
                "order" => 7,
            ),
            array(
                "id" => 107,
                "data_type_id" => 4,
                "field" => "id",
                "type" => "number",
                "display_name" => "Id",
                "required" => 1,
                "browse" => 0,
                "read" => 0,
                "edit" => 0,
                "add" => 0,
                "delete" => 0,
                "details" => "{}",
                "order" => 1,
            ),
            array(
                "id" => 108,
                "data_type_id" => 4,
                "field" => "name",
                "type" => "text",
                "display_name" => "Name",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 2,
            ),
            array(
                "id" => 109,
                "data_type_id" => 4,
                "field" => "surname",
                "type" => "text",
                "display_name" => "Surname",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 3,
            ),
            array(
                "id" => 110,
                "data_type_id" => 4,
                "field" => "email",
                "type" => "text",
                "display_name" => "Email",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 7,
            ),
            array(
                "id" => 111,
                "data_type_id" => 4,
                "field" => "password",
                "type" => "text",
                "display_name" => "Password",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 5,
            ),
            array(
                "id" => 112,
                "data_type_id" => 4,
                "field" => "address",
                "type" => "text",
                "display_name" => "Address",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 6,
            ),
            array(
                "id" => 113,
                "data_type_id" => 4,
                "field" => "phone",
                "type" => "number",
                "display_name" => "Phone",
                "required" => 1,
                "browse" => 1,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 7,
            ),
            array(
                "id" => 17,
                "data_type_id" => 4,
                "field" => "view",
                "type" => "number",
                "display_name" => "View",
                "required" => 0,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 8,
            ),
            array(
                "id" => 16,
                "data_type_id" => 4,
                "field" => "rating",
                "type" => "number",
                "display_name" => "Rating",
                "required" => 0,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 9,
            ),
            array(
                "id" => 116,
                "data_type_id" => 4,
                "field" => "status",
                "type" => "checkbox",
                "display_name" => "Status",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 10,
            ),
            array(
                "id" => 117,
                "data_type_id" => 4,
                "field" => "image",
                "type" => "image",
                "display_name" => "Image",
                "required" => 1,
                "browse" => 0,
                "read" => 1,
                "edit" => 1,
                "add" => 1,
                "delete" => 1,
                "details" => "{}",
                "order" => 11,
            ),
            array(
                "id" => 118,
                "data_type_id" => 4,
                "field" => "created_at",
                "type" => "timestamp",
                "display_name" => "Created At",
                "required" => 0,
                "browse" => 0,
                "read" => 0,
                "edit" => 0,
                "add" => 0,
                "delete" => 0,
                "details" => "{}",
                "order" => 12,
            ),
            array(
                "id" => 15,
                "data_type_id" => 4,
                "field" => "updated_at",
                "type" => "timestamp",
                "display_name" => "Updated At",
                "required" => 0,
                "browse" => 0,
                "read" => 0,
                "edit" => 0,
                "add" => 0,
                "delete" => 0,
                "details" => "{}",
                "order" => 13,
            ),
        ];

        foreach($dataRows as $dataRow) {
            DataRow::firstOrCreate(
                ['id' => $dataRow['id']],
                $dataRow
            );
        }
    }
}
